---
- name: Install Python PIP
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    pythonremove:
      ["python3-keyring",
      "python3-pyasn1",
      "python3-keyrings.alt",
      "python3-wheel",
      "python3-setuptools",
      "python-six",
      "python-idna"
      ]

    pythonremovemodules:
      ["PyGObject",
      "pyxdg",
      "pycrypto",
      "astral"
      ]

    pythoninstall:
      ["RPi.GPIO",
      "requests",
      "pymodbus",
      "pymysql",
      "wheel",
      "awake",
      "setuptools",
      "pycrypto",
      "yolk3k"
      ]


  tasks:
  - name: remove apt
    apt:
      name: "{{ item }}"
      state: absent
      autoremove: yes
      autoclean: yes
      purge: yes
    with_items: "{{ pythonremove }}"

  - name: Add src
    replace:
      destfile: /etc/apt/sources.list
      regexp: "^#deb-src"
      replace: "deb-src"
    ignore_errors: yes

  - name: Fix
    command: 'apt-get -f -y install'
    register: fix
  - debug: var=fix

  - name: remove modules
    pip:
      name: "{{ item }}"
      state: absent
      executable: pip3
    with_items: "{{ pythonremovemodules }}"

  - name: Install libffi-dev
    apt:
      name: libffi-dev
      state: latest
      install_recommends: no
    register: libffi
  - debug: msg='libffi Installation "{{ libffi }}"'

  - name: Install libssl-dev
    apt:
      name: libssl-dev
      state: latest
      install_recommends: no
    register: libssl
  - debug: msg='libssl Installation "{{ libssl }}"'

  - name: Install pip3
    command: "/usr/local/bin/easy_install-3.5 pip"

  - name: Install pip
    command: "/usr/local/bin/easy_install pip"

  - name: Install packages
    pip:
      name: "{{ item }}"
      executable: pip3
      state: latest
    become: true
    become_user: root
    with_items: "{{ pythoninstall }}"
