---
- name: Install Python Packages
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    pythonremove:
      ["python3-keyring",
      "python3-pyasn1",
      "python3-keyrings.alt",
      "python3-wheel",
      "python3-setuptools",
      "python-six",
      "python-idna"
      ]

    pythonremovemodules:
      ["pyxdg",
      "pycrypto",
      "astral"
      ]

    pythoninstall:
      ["RPi.GPIO",
      "requests",
      "pymodbus",
      "pymysql",
      "wheel",
      "awake",
      "setuptools",
      "pycrypto",
      "yolk3k",
      "snmp",
      "knxPython",
      "spur"
      ]


  tasks:
  - name: remove apt
    apt:
      name: "{{ item }}"
      state: absent
      autoremove: yes
      autoclean: yes
      purge: yes
    with_items: "{{ pythonremove }}"
    ignore_errors: yes

  - name: Add src
    replace:
      destfile: /etc/apt/sources.list
      regexp: "^#deb-src"
      replace: "deb-src"
    ignore_errors: yes

  - name: Fix
    command: 'apt-get -f -y install'

  - name: Install libffi-dev
    apt:
      name: libffi-dev
      state: latest
      install_recommends: no

  - name: Install libssl-dev
    apt:
      name: libssl-dev
      state: latest
      install_recommends: no

  - name: download get-pip
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /opt/

  - name: Install pip3
    command: "python3 /opt/get-pip.py"

  - name: Install pip
    command: "python2.7 /opt/get-pip.py"

  - name: remove modules
    pip:
      name: "{{ item }}"
      state: absent
      executable: pip3
    with_items: "{{ pythonremovemodules }}"

  - name: Install modules
    pip:
      name: "{{ item }}"
      executable: pip3
      state: latest
    become: true
    become_user: root
    with_items: "{{ pythoninstall }}"

  - name: pygobjectfiles
    find:
      paths: /usr/lib/python3/dist-packages/
      patterns: "pygobject*"
    register: pygobject_to_delete

  - name: Remove pygobject
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ pygobject_to_delete.files }}"
    ignore_errors: yes
    register: deleted
  - debug: var=deleted
