---
- name: Install SmarthomeNG
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    apt_install:
      ["dialog",
      "rlwrap",
      "libatlas-base-dev",
      "libblas-dev",
      "liblapack-dev",
      "libopenblas-base",
      "libopenblas-dev"
      ]

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: install apt
    apt:
      name: "{{ item }}"
      state: latest
      autoremove: yes
      autoclean: yes
    with_items: "{{ apt_install }}"

  - name: Git SmarthomeNG
    git:
      repo: 'git://github.com/smarthomeNG/smarthome.git'
      dest: /usr/local/smarthome
      version: master
      force: yes
    register: git
  - debug: var=git

  - name: Git Plugins
    git:
      repo: 'git://github.com/smarthomeNG/plugins.git'
      dest: /usr/local/smarthome/plugins
      version: master
      force: yes
    register: git2
    ignore_errors: yes
  - debug: var=git2

  - name: plugins ignore perm
    command: git config core.fileMode false chdir=/usr/local/smarthome/plugins

  - name: sh ignore perm
    command: git config core.fileMode false chdir=/usr/local/smarthome/

  - name: Create logic yaml
    file:
      path: /usr/local/smarthome/etc/logic.yaml
      state: touch
      owner: smarthome
      group: smarthome
      mode: 0755

  - name: Copy smarthome yaml
    copy:
      remote_src: True
      src: /usr/local/smarthome/etc/smarthome.yaml.default
      dest: /usr/local/smarthome/etc/smarthome.yaml

  - name: Copy logging yaml
    copy:
      remote_src: True
      src: /usr/local/smarthome/etc/logging.yaml.default
      dest: /usr/local/smarthome/etc/logging.yaml

  - name: Change requirements
    file:
      path: /usr/local/smarthome/tools/build_requirements.py
      mode: 0777

  - name: Update requirements
    command: /usr/local/smarthome/tools/build_requirements.py

  - name: Install requirements
    pip: requirements=/usr/local/smarthome/requirements/all.txt executable=pip3 state=latest
    become: true
    become_user: root

  - name: Install pymysql
    pip: name=pymysql executable=pip3 state=latest
    become: true
    become_user: root

  - name: Install yolk3k
    pip: name=yolk3k executable=pip3 state=latest
    become: true
    become_user: root

  - name: Update modules
    command: /usr/local/bin/yolk --upgrade

  - name: Downgrade to requirements
    pip: requirements=/usr/local/smarthome/requirements/all.txt executable=pip3
    become: true
    become_user: root

  - name: Copy Service
    copy:
      dest: /lib/systemd/system/smarthome.service
      src: configs/smarthome.service

  - name: Change Owner
    file:
      path: /usr/local/smarthome
      owner: smarthome
      group: smarthome
      mode: 0775
      recurse: yes
      state: directory

  - name: Remove astral
    pip: name=astral executable=pip3 state=absent

  - name: Restart smarthome service
    systemd: state=restarted name=smarthome.service

  - name: enable_service
    systemd: enabled=yes name=smarthome.service

  - name: List Modules
    command: "yolk --list"
    register: pip3
    ignore_errors: yes
  - debug: var=pip3
