---
- name: Install Samba
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    samba_users:
      - name: smarthome
        password: ''

  tasks:
  - name: Install Samba
    apt: name=samba force=no state=latest

  - name: Copy config
    copy:
      dest: /etc/samba/smb.conf
      src: configs/samba.conf

  - name: Create Samba users
    shell: >
      (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
      || (echo {{ item.password }}; echo {{ item.password }}) \
      | smbpasswd -s -a {{ item.name }}
    with_items: "{{ samba_users }}"
    register: create_user_output
    changed_when: "'Added user' in create_user_output.stdout"

  - name: chmod conf
    file:
      path: /etc/samba/smbd.conf
      state: touch
      owner: smarthome
      group: smarthome
      mode: 0755

  - name: Restart smbd
    systemd: state=restarted name=smbd
    notify: Enable smbd

  handlers:
    - name: Enable smbd
      systemd: enabled=yes name=smbd
