---
- name: Install susvd
  hosts: public
  remote_user: root
  become_user: root
  become: true


  tasks:
  
  - name: Download Driver
    get_url:
      url: http://seprotronic.com/susv/files/software/susvd-en-2.2-systemd-all.tar.gz
      dest: /root
      mode: 0777
    register: download  
  - debug: var=download
    
  - name: Extract susvd
    unarchive:
      src: /root/susvd-en-2.2-systemd-all.tar.gz
      dest: /root/ 
      remote_src: true  
    register: extract  
  - debug: var=extract

  - name: Remove tgz
    file: path=/root/susvd-en-2.2-systemd-all.tar.gz state=absent

  - name: Make deb dir
    file: path=/etc/deb-files state=directory

  - name: Copy deb file
    copy: remote_src=True src=/root/susvd-en-2.2-systemd-all.deb dest=/etc/deb-files

  - name: Install susvd
    apt:
      deb: /etc/deb-files/susvd-en-2.2-systemd-all.deb
      state: present
    register: susvd
  - debug: var=susvd

  - name: Test for dtparam
    shell: grep "^dtparam=i2c1=on" /boot/config.txt
    register: test_grep1
    ignore_errors: yes
  
  - name: config i2c
    lineinfile:
      path: /boot/config.txt
      insertafter: EOF
      line: 'dtparam=i2c1=on'
    when: test_grep1.stdout == ""

  - name: Test for line
    shell: grep "^dtparam=i2c_arm=on" /boot/config.txt
    register: test_grep2
    ignore_errors: yes
    
  - name: config i2c_arm
    lineinfile:
      path: /boot/config.txt
      insertafter: EOF
      line: 'dtparam=i2c_arm=on'
    when: test_grep2.stdout == ""

  - name: Test for line
    shell: grep "^i2c-dev" /etc/modules
    register: test_grep3
    ignore_errors: yes

  - name: Modules
    lineinfile:
      path: /etc/modules
      insertafter: EOF
      line: 'i2c-dev'
    when: test_grep3.stdout == ""

  - name: timer
    command: '/opt/susvd/susv -timer -1'
    ignore_errors: yes

  - name: auto off
    command: '/opt/susvd/susv -auto 0'
    ignore_errors: yes

  - name: start
    command: '/opt/susvd/susvd -stop'
    ignore_errors: yes

  - name: Delete deb
    file: path=/root/susvd-en-2.2-systemd-all.deb state=absent

  - name: Chmod susvd
    file: 
      path: /etc/systemd/system/susvd.service
      mode: 0644
      

