---
- name: Install Squeezelite
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    packages_compile:
      ["libasound2-dev",
      "libflac-dev",
      "libmad0-dev",
      "libvorbis-dev",
      "libfaad-dev",
      "libmpg123-dev",
      "ffmpeg"]

    packages:
      ["ffmpeg"]

  tasks:
  - name: Install Packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      install_recommends: no
    with_items: "{{ packages }}"

  - name: Copy squeezelite
    copy:
      src: executables/squeezelite
      dest: /usr/bin/
      mode: 0755

  - name: Copy squeezelite-ffmpeg
    copy:
      src: executables/squeezelite-ffmpeg
      dest: /usr/bin/
      mode: 0755

  - name: Copy squeezelite sh
    copy:
      src: executables/squeezelite.sh
      dest: /usr/local/bin/
      mode: 0777

  - name: Copy squeezelite service
    copy:
      src: configs/squeezelite.service
      dest: /lib/systemd/system/

  - name: Create log file
    file:
      path: /var/log/squeezelite.log
      state: touch
      owner: smarthome
      group: smarthome
      mode: 0755
