---
- name: Install OpenVPN
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:

  - name: Install openvpn
    apt: name=openvpn force=no state=latest install_recommends=yes

  - name: easy_dir
    file:
      path: /etc/ssl/easy-rsa
      state: directory
      mode: 0755

  - name: Copy easyrsa
    unarchive:
      src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/EasyRSA-unix-v3.0.6.tgz
      dest: /etc/ssl/easy-rsa
      remote_src: yes
      validate_certs: False
      extra_opts: [--strip-components=1]

  - name: Copy config
    copy:
      src: configs/openvpn.conf
      dest: /etc/openvpn/server.conf
      mode: 0644

  - name: Copy client
    copy:
      src: configs/openvpn_client_example.conf
      dest: /home/smarthome/openvpn_client_example.conf
      mode: 0644

  - name: ip4
    replace:
      destfile: /etc/sysctl.conf
      regexp: "^#net.ipv4.ip_forward=1"
      replace: "net.ipv4.ip_forward=1"
    ignore_errors: yes

  - name: store sysctl
    shell: "sysctl -p"
    register: sysctl
  - debug: var=sysctl

  - name: Install iptables
    apt: name=iptables-persistent force=no state=latest

  - name: iptables script
    blockinfile:
      path: /usr/local/bin/iptables_openvpn.sh
      mode: 0777
      owner: smarthome
      group: smarthome
      create: yes
      block: |
        #!/bin/bash
        iptables -t filter -F
        iptables -t nat -F
        iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
        iptables -A FORWARD -i tun0 -j ACCEPT
        iptables -A FORWARD -j REJECT
        iptables -t nat -A POSTROUTING -s '10.8.0.0/24' -j MASQUERADE
        iptables-save > /etc/iptables/rules.v4

  - name: run iptables
    shell: "/usr/local/bin/iptables_openvpn.sh"
    register: iptables
  - debug: var=iptables

  - name: Copy logrotate
    copy:
      src: configs/logrotate_openvpn
      dest: /etc/logrotate.d/openvpn
      mode: 0644

  - name: disable openvpn
    systemd: enabled=no name=openvpn.service
