---
- name: Install freeradius
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:

  - name: easy_dir
    file:
      path: /etc/ssl/easy-rsa
      state: directory
      mode: 0755

  - name: Copy easyrsa
    unarchive:
      src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.4/EasyRSA-3.0.4.tgz
      dest: /etc/ssl/easy-rsa
      remote_src: yes
      validate_certs: False
      extra_opts: [--strip-components=1]
      
  - name: Install freeradius
    apt: name=freeradius force=no state=latest install_recommends=no

  - name: Stop freeradius
    systemd: state=stopped name=freeradius

  - name: disable freeradius
    systemd: enabled=no name=freeradius.service

  - name: log
    replace:
      destfile: /etc/freeradius/3.0/radiusd.conf
      regexp: "auth = no"
      replace: "auth = yes"
    ignore_errors: yes

  - name: Copy eap
    copy:
      src: configs/freeradius_eap.conf
      dest: /etc/freeradius/3.0/mods-enabled/eap
      mode: 0600
      owner: freerad
      group: freerad

  - name: Copy clients
    copy:
      src: configs/freeradius_clients.conf
      dest: /etc/freeradius/3.0/clients.conf
      mode: 0600
      owner: freerad
      group: freerad

  - name: Groups pi
    user:
      name: pi
      groups: freerad
      append: yes

  - name: Groups smarthome
    user:
      name: smarthome
      groups: freerad
      append: yes

  - name: Groups logcheck
    user:
      name: logcheck
      groups: freerad
      append: yes
