---
- name: Install freeradius
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:

  - name: easy_dir
    file:
      path: /etc/ssl/easy-rsa
      state: directory
      mode: 0755

  - name: Copy easyrsa
    unarchive:
      src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/EasyRSA-unix-v3.0.6.tgz
      dest: /etc/ssl/easy-rsa
      remote_src: yes
      validate_certs: False
      extra_opts: [--strip-components=1]

  - name: Install freeradius
    apt: name=freeradius force=no state=latest install_recommends=no

  - name: Stop freeradius
    systemd: state=stopped name=freeradius

  - name: disable freeradius
    systemd: enabled=no name=freeradius.service

  - name: log
    replace:
      destfile: /etc/freeradius/3.0/radiusd.conf
      regexp: "auth = no"
      replace: "auth = yes"
    ignore_errors: yes

  - name: Copy eap
    copy:
      src: configs/freeradius_eap.conf
      dest: /etc/freeradius/3.0/mods-enabled/eap
      mode: 0600
      owner: freerad
      group: freerad

  - name: Copy clients
    copy:
      src: configs/freeradius_clients.conf
      dest: /etc/freeradius/3.0/clients.conf
      mode: 0600
      owner: freerad
      group: freerad

  - name: Copy attrfilter
    copy:
      src: configs/freeradius_attr_filter.conf
      dest: /etc/freeradius/3.0/mods-config/attr_filter/access_reject
      mode: 0640
      owner: freerad
      group: freerad

  - name: disable_ldap1
    replace:
      destfile: /etc/freeradius/3.0/sites-enabled/default
      regexp: "-ldap"
      replace: "#-ldap"
    ignore_errors: yes

  - name: disable_sql1
    replace:
      destfile: /etc/freeradius/3.0/sites-enabled/default
      regexp: "-sql"
      replace: "#-sql"
    ignore_errors: yes

  - name: disable_ldap2
    replace:
      destfile: /etc/freeradius/3.0/sites-enabled/inner-tunnel
      regexp: "-ldap"
      replace: "#-ldap"
    ignore_errors: yes

  - name: disable_sql2
    replace:
      destfile: /etc/freeradius/3.0/sites-enabled/inner-tunnel
      regexp: "-sql"
      replace: "#-sql"
    ignore_errors: yes

  - name: disable_pap1
    replace:
      destfile: /etc/freeradius/3.0/sites-enabled/default
      regexp: "pap"
      replace: "#pap"
    ignore_errors: yes

  - name: disable_pap2
    replace:
      destfile: /etc/freeradius/3.0/sites-enabled/inner-tunnel
      regexp: "pap"
      replace: "#pap"
    ignore_errors: yes

  - name: Groups pi
    user:
      name: pi
      groups: freerad
      append: yes

  - name: Groups smarthome
    user:
      name: smarthome
      groups: freerad
      append: yes

  - name: Groups logcheck
    user:
      name: logcheck
      groups: freerad
      append: yes
