---
- name: Install MQTT
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    deps:
      ["adduser",
      "libuuid1",
      "uuid-dev",
      "lsb-base",
      "libwebsockets8",
      "libwrap0",
      "libc-ares2",
      "libc6",
      "libssl1.1",
      "libc-ares-dev"
      ]

  tasks:
  - name: Install paho-mqtt
    pip: name=paho-mqtt executable=pip3

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items: "{{ deps }}"

  - name: Create deb-files directory
    file: path=/etc/deb-files/ state=directory mode=0755

  - name: Copy deb files
    copy:
      src: "{{ item }}"
      dest: /etc/deb-files/
    with_fileglob:
      - packages/mosquitto*

  - name: Create User
    user:
      name: mosquitto
      shell: /dev/null
      groups: users
      createhome: no
      comment: 'Mosquitto User'

  - name: Install
    apt:
      deb: /etc/deb-files/mosquitto_1.5-1_armhf.deb
      force: yes

  - name: ldconfig
    command: "ldconfig"
    args:
      chdir: /sbin

  - name: Copy config
    copy:
      src: /etc/mosquitto/mosquitto.conf.example
      dest: /etc/mosquitto/mosquitto.conf
      remote_src: True
      owner: smarthome

  - name: Change config
    replace:
      destfile: /etc/mosquitto/mosquitto.conf
      regexp: "^#pid_file"
      replace: "pid_file /var/run/mosquitto/mosquitto.pid"

  - name: create directory
    file:
      path: /var/log/mosquitto
      state: directory
      mode: 0755
      owner: mosquitto
      group: mosquitto

  - name: logdest
    blockinfile:
      path: "/etc/mosquitto/mosquitto.conf"
      block: |
        log_dest syslog
        log_type notice
        log_facility 0
        log_timestamp false
    ignore_errors: yes

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/mosquitto.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname == 'mosquitto' or $msg contains 'Mosquitto' then {
          action(type="omfile" file="/var/log/mosquitto/mosquitto.log" template="FileFormat_timestamp")
          stop
        }
    ignore_errors: yes

  - name: rsyslog
    systemd: state=restarted name=rsyslog.service
    
  - name: Copy service
    copy:
      src: configs/mosquitto.service
      dest: /lib/systemd/system/mosquitto.service
      owner: root
      group: root
      mode: 0644
