---
- name: Install MQTT
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Install paho-mqtt
    pip: name=paho-mqtt executable=pip3

  - name: add apt-key
    apt_key:
      url: http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
      state: present

  - name: add repository
    apt_repository:
      repo: deb https://repo.mosquitto.org/debian stretch main
      state: present
      filename: mosquitto
      update_cache: yes

  - name: Create User
    user:
      name: mosquitto
      shell: /dev/null
      groups: users
      createhome: no
      comment: 'Mosquitto User'

  - name: Install
    apt:
      name: "mosquitto"
      state: latest
      update_cache: yes

  - name: create directory
    file:
      path: /var/log/mosquitto
      state: directory
      mode: 0755
      owner: mosquitto
      group: mosquitto

  - name: logdest
    blockinfile:
      path: "/etc/mosquitto/mosquitto.conf"
      block: |
        log_dest syslog
        log_type notice
        log_facility 0
        log_timestamp false
    ignore_errors: yes

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/mosquitto.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname == 'mosquitto' or $msg contains 'Mosquitto' then {
          action(type="omfile" file="/var/log/mosquitto/mosquitto.log" template="FileFormat_timestamp")
          stop
        }
    ignore_errors: yes

  - name: rsyslog
    systemd: state=restarted name=rsyslog.service
