# plugin.yaml
# Der BackendServer stellt eine Übersicht zur Laufzeit dar und liefert Informationen ähnlich wie das CLI Plugin
# Der Zugriff erfolgt über http://<IP oder Name des SmartHomeNG Servers bzw. ip>:<port>
# port wird als Attribut weiter unten definiert
# das Passwort ist zunächst im Klartext anzugeben. In neueren Versionen wird es eine Funktion im Backend geben,
# die aus einem gegebenen Passwort einen Hash erzeugt. Wenn user oder password fehlen gibt es keine Abfrage
BackendServer:
    class_name: BackendServer
    class_path: plugins.backend
    port: 8383
    updates_allowed: 'True'
    threads: 8
    user: ''
    password: ''
    language: de

# KNX Verbindung via knxd
knx:
    class_name: KNX
    class_path: plugins.knx
    host: 127.0.0.1
    port: 6720
    # send_time: 600 # update date/time every 600 seconds, default none
    # time_ga: 1/1/1 # default none
    # date_ga: 1/1/2 # default none

# Bereitstellung eines Websockets zur Kommunikation zwischen SmartVISU und SmartHomeNG
visu:
    class_name: WebSocket
    class_path: plugins.visu_websocket
    # ip: 0.0.0.0
    # port: 2424
    # tls: no
    wsproto: 4
    acl: rw

# Autogenerierung von Webseiten für SmartVISU
smartvisu:
    class_name: SmartVisu
    class_path: plugins.visu_smartvisu
    # '"neue" Linux Versionen (z.B. Debian > 8.x, Ubuntu > 14.x)'
    smartvisu_dir: /var/www/html/smartVISU

    # nur \"alte\" Linux-Variationen
    # smartvisu_dir: /var/www/smartVISU
    # generate_pages: True
    # handle_widgets: True
    # overwrite_templates: Yes
    # visu_style: blk

# Command Line Interface
# wichtig für Funktionsprüfungen solange keine Visu zur Verfügung steht
cli:
    class_name: CLI
    class_path: plugins.cli
    ip: 0.0.0.0
    update: 'True'

# SQL-Treiber, unterstützt auch die SmartVISU 2.8/2.9
# dazu muß im websocket plugin zwingend die Protokollversion 4 eingetragen sein
sql:
    class_name: SQL
    class_path: plugins.sqlite_visu2_8

# Onewire Plugin
# [ow]
# class_name: OneWire
# class_path: plugins.onewire

# memlog:
#     class_name: MemLog
#     class_path: plugins.memlog
#     name: alert

# ow:
#     class_name: OneWire
#     class_path: plugins.onewire
#     host: 127.0.0.1
#     port: 4304

# apcups:
#     class_name: APCUPS
#     class_path: plugins.apcups
#     host: localhost
#     port: 3551

# dmx1:
#     class_name: ArtNet
#     class_path: plugins.artnet
#     artnet_subnet: 0
#     artnet_net: 0
#     artnet_universe: 0
#     ip: 192.168.1.123
#     port: 6454

# ast:
#     class_name: Asterisk
#     class_path: plugins.asterisk
#     username: admin
#     password: secret
#     host: 127.0.0.1    # default
#     port: 5038    # default

# fb1:
#     class_name: AVM
#     class_path: plugins.avm
#     username: ...    # optional
#     password: '...'
#     host: fritz.box
#     port: 49443
#     cycle: 300
#     ssl: True    # use https or not
#     verify: False    # verify ssl certificate
#     call_monitor: 'True'
#     call_monitor_incoming_filter: "...    ## optional, don't set if you don't want to watch only one specific number with your call monitor"
#     avm_identifier: fritzbox_1

# boxcar:
#     class_name: Boxcar
#     class_path: plugins.boxcar
#     apikey: abcdefghij123456    # Get it from your Boxcar Account
#     email: your@mail.org    # Registered with Boxcar

# comfoair:
#     class_name: ComfoAir
#     class_path: plugins.comfoair
#     kwltype: comfoair350    # Currently supported: comfoair350 and comfoair500
#     host: 192.168.123.6    # Provide host and port if you want to use TCP connection (for a TCP to serial converter)
#     port: 5555    # Port
#     serialport: /dev/ttyUSB0    # Enable this if you want to use a serial connection

# datalog:
#     class_name: DataLog
#     class_path: plugins.datalog
#     path: var/log/data
#     filepatterns:
#       - default:{log}-{year}-{month}-{day}.csv
#       - yearly:{log}-{year}.csv
#     logpatterns: csv:{time};{item};{value}\n
#     cycle: 300

# dlms:
#     class_name: DLMS
#     class_path: plugins.dlms
#     serialport: /dev/ttyO1
#     baudrate: 300    # default 300
#     update_cycle: 20    # default 20
#     use_checksum: no    # default no
#     reset_baudrate: no    # default no
#     no_waiting: yes    # default yes

# dmx:
#     class_name: DMX
#     class_path: plugins.dmx
#     tty: /dev/usbtty...
#     interface: nanodmx

# DuW:
#     class_name: DuW
#     class_path: plugins.drexelundweiss
#     tty: /dev/ttyUSB0
#     Busmonitor: 1
#     LU_ID: 130
#     WP_ID: 140

# squeezebox:
#     class_name: Squeezebox
#     class_path: plugins.squeezebox
#     host: squeezeserver
#     # port: <port>

# uzsu:
#     class_name: UZSU
#     class_path: plugins.uzsu

# simulation:
#     class_name: Simulation
#     class_path: plugins.simulation
#     data_file: /usr/local/smarthome/var/db/simulation.txt

# nw:
#     class_name: Network
#     class_path: plugins.network
#     ip: 0.0.0.0
#     port: 2727
#     http: 8765
#     tcp_acl:
#       - 127.0.0.1
#       - 192.168.0.34
#     udp: 'no'
#     udp_acl: '*'

# wol:
#     class_name: WakeOnLan
#     class_path: plugins.wol

# homematic:
#     class_name: Homematic
#     class_path: plugins.homematic
#     host: 192.168.50.250
#     port: 2001
