---
- name: Install MQTT
  hosts: public
  remote_user: root
  become_user: root
  become: true

  vars:
    deps:
      ["adduser",
      "libuuid1",
      "uuid-dev",
      "lsb-base",
      "libwebsockets8",
      "libwrap0",
      "libc-ares2",
      "libc6",
      "libssl1.1",
      "libc-ares-dev"
      ]

  tasks:
  - name: Install paho-mqtt
    pip: name=paho-mqtt executable=pip3

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items: "{{ deps }}"

  - name: Download source
    unarchive:
      src: http://mosquitto.org/files/source/mosquitto-1.4.14.tar.gz
      dest: /root/
      remote_src: yes

  - name: Install xsltproc
    apt: name=xsltproc force=no state=latest install_recommends=no
    register: xsltproc
  - debug: var=xsltproc

  - name: Install docbook-xsl
    apt: name=docbook-xsl force=no state=latest install_recommends=no
    register: docbook-xsl
  - debug: var=docbook-xsl

  - name: make
    command: "make"
    args:
      chdir: /root/mosquitto-1.4.14

  - name: checkinstall
    command: "checkinstall --install=no --pkgversion=1.4.14 --pkgname=Mosquitto --nodoc"
    args:
      chdir: /root/mosquitto-1.4.14

  - name: Copy deb files
    copy:
      remote_src: True
      src: "/root/mosquitto-1.4.14/mosquitto_1.4.14-1_armhf.deb"
      dest: /etc/deb-files/

  - name: Git mosquitto
    git:
      repo: 'https://github.com/eclipse/mosquitto.git'
      dest: /root/mosquitto
      version: develop
    register: git
  - debug: var=git

  - name: make-client
    command: "make"
    args:
      chdir: /root/mosquitto/client

  - name: checkinstall-client
    command: "checkinstall --install=no --pkgversion=1.4.14 --pkgname=mosquitto-clients --nodoc"
    args:
      chdir: /root/mosquitto/client

  - name: Copy deb files-client
    copy:
      remote_src: True
      src: "/root/mosquitto/client/mosquitto-clients_1.4.14-1_armhf.deb"
      dest: /etc/deb-files/

  - name: make-lib
    command: "make"
    args:
      chdir: /root/mosquitto/lib

  - name: checkinstall-lib
    command: "checkinstall --install=no --pkgversion=1.4.14 --pkgname=mosquitto-lib --nodoc"
    args:
      chdir: /root/mosquitto/lib

  - name: Copy deb files-lib
    copy:
      remote_src: True
      src: "/root/mosquitto/lib/mosquitto-lib_1.4.14-1_armhf.deb"
      dest: /etc/deb-files/

  - name: Create User
    user:
      name: mosquitto
      shell: /dev/null
      groups: users
      createhome: no
      comment: 'Mosquitto User'

  - name: Install-lib
    apt:
      deb: /etc/deb-files/mosquitto-lib_1.4.14-1_armhf.deb
      force: yes

  - name: Install
    apt:
      deb: /etc/deb-files/mosquitto_1.4.14-1_armhf.deb

  - name: Delete mqtt dir
    file: path=/root/mosquitto-1.4.14/ state=absent

  - name: Install-client
    apt:
      deb: /etc/deb-files/mosquitto-clients_1.4.14-1_armhf.deb
      force: yes

  - name: ldconfig
    command: "ldconfig"
    args:
      chdir: /sbin

  - name: Delete mosquitto dir
    file: path=/root/mosquitto/ state=absent

  - name: Copy config
    copy:
      src: /etc/mosquitto/mosquitto.conf.example
      dest: /etc/mosquitto/mosquitto.conf
      remote_src: True
      owner: smarthome

  - name: Copy service
    copy:
      src: configs/mosquitto.service
      dest: /lib/systemd/system/mosquitto.service
      owner: root
      group: root
      mode: 0644

  - name: Change config
    replace:
      destfile: /etc/mosquitto/mosquitto.conf
      regexp: "^#pidfile"
      replace: "pid_file /var/run/mosquitto/mosquitto.pid"

  - name: create directory
    file:
      path: /var/log/mosquitto
      state: directory
      mode: 0755
      owner: mosquitto
      group: mosquitto

  - name: logdest
    blockinfile:
      path: "/etc/mosquitto/mosquitto.conf"
      block: |
        log_dest file /var/log/mosquitto/mosquitto.log
        log_type notice
    ignore_errors: yes

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/mosquitto.conf"
      create: yes
      block: |
        if $programname == 'mosquitto' then {
          action(type="omfile" file="/var/log/mosquitto/mosquitto.log")
          stop
        }
    ignore_errors: yes
