---
- name: Install Homebdrige
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Install Avahi
    apt: name=libavahi-compat-libdnssd-dev force=no state=latest update_cache=yes

  - name: Install Avahi-Utils
    apt: name=avahi-utils force=no state=latest update_cache=yes

  - name: Install NodeJS
    apt: name=nodejs force=yes state=latest update_cache=yes

  - name: Install Homebridge
    shell: npm install -g --unsafe-perm homebridge
    register: npm
  - debug: var=npm

  - name: Rebuild npm
    shell: npm rebuild
    args:
      chdir: /usr/lib/node_modules/homebridge
    register: rebuildnpm
    ignore_errors: true
  - debug: var=rebuildnpm

  - name: logfile
    blockinfile:
      dest: "/etc/rsyslog.d/homebridge.conf"
      create: yes
      block: |
        if $programname == 'homebridge' then {
          action(type="omfile" file="/var/log/homebridge.log")
          stop
        }
    ignore_errors: yes

  - name: Install people
    shell: npm install -g homebridge-people
    register: npm

  - debug: var=npm

  - name: Install Forever
    shell: npm install -g forever
    register: npm

  - debug: var=npm

  - name: Install Plugin
    shell: npm install -g homebridge-smarthomeng --unsafe-perm
    register: npm

  - debug: var=npm

  - name: dir
    file:
      path: /home/smarthome/.homebridge
      state: directory
      owner: smarthome
      group: smarthome

  - name: Copy private config
    copy:
      src: ../private/homebridge_config.json
      dest: /home/smarthome/.homebridge/config.json
      owner: smarthome
      group: smarthome
      mode: 775
    when: "inventory_hostname == 'wz'"

  - name: Copy config
    copy:
      src: ../configs/homebridge_config.json
      dest: /home/smarthome/.homebridge/config.json
      owner: smarthome
      group: smarthome
      mode: 775
    when: "not inventory_hostname == 'wz'"

  - name: Copy service
    copy:
      src: ../configs/homebridge.service
      dest: /lib/systemd/system/homebridge.service
      owner: root
      group: root
      mode: 0644


  - name: Copy Logcheck
    copy:
      src: ../configs/logcheck.homebridge
      dest: /etc/logcheck/ignore.d.server/homebridge
      owner: root
      group: logcheck
      mode: 0644


  - name: Restart Service
    systemd: state=restarted name=homebridge.service
    notify: enable_service


  handlers:
  - name: enable_service
    systemd: enabled=yes name=homebridge.service
