---
- name: Install Homebdrige
  hosts: public
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Download nodeJS
    get_url:
      url: https://raw.githubusercontent.com/nodesource/distributions/master/deb/setup_8.x
      dest: /root
      mode: 775
    register: curl
    when: "inventory_hostname == 'wz'"
  - debug: var=curl

  - name: Run Setup
    shell: /root/setup_8.x
    register: setup
    when: "inventory_hostname == 'wz'"
  - debug: var=setup

  - name: Install NodeJS
    apt: name=nodejs force=no state=latest update_cache=yes
    when: "inventory_hostname == 'wz'"

  - name: Install Avahi
    apt: name=libavahi-compat-libdnssd-dev force=no state=latest update_cache=yes
    when: "inventory_hostname == 'wz'"

  - name: Install Avahi-Utils
    apt: name=avahi-utils force=no state=latest update_cache=yes
    when: "inventory_hostname == 'wz'"

  - name: Install Homebridge
    shell: npm install -g --unsafe-perm homebridge
    register: npm
    when: "inventory_hostname == 'wz'"
  - debug: var=npm

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/homebridge.conf"
      create: yes
      block: |
        if $programname == 'homebridge' then {
          action(type="omfile" file="/var/log/homebridge.log")
          stop
        }
    ignore_errors: yes
    when: "inventory_hostname == 'wz'"

  - name: Install people
    shell: npm install -g homebridge-people
    register: npm
    when: "inventory_hostname == 'wz'"
  - debug: var=npm

  - name: Install Forever
    shell: npm install -g forever
    register: npm
    when: "inventory_hostname == 'wz'"
  - debug: var=npm

  - name: Install Plugin
    shell: npm install -g homebridge-smarthomeng --unsafe-perm
    register: npm
    when: "inventory_hostname == 'wz'"
  - debug: var=npm

  - name: dir
    file:
      path: /home/smarthome/.homebridge
      state: directory
      owner: smarthome
      group: smarthome
    when: "inventory_hostname == 'wz'"

  - name: Copy config
    copy:
      src: private/homebridge_config.json
      dest: /home/smarthome/.homebridge/config.json
      owner: smarthome
      group: smarthome
      mode: 775
    when: "inventory_hostname == 'wz'"

  - name: Copy service
    copy:
      src: configs/homebridge.service
      dest: /lib/systemd/system/homebridge.service
      owner: root
      group: root
      mode: 0644
    when: "inventory_hostname == 'wz'"

  - name: Copy Logcheck
    copy:
      src: configs/logcheck.homebridge
      dest: /etc/logcheck/ignore.d.server/homebridge
      owner: root
      group: logcheck
      mode: 0644
    when: "inventory_hostname == 'wz'"

  - name: Restart Service
    systemd: state=restarted name=homebridge.service
    notify: disable_service
    when: "inventory_hostname == 'wz'"

  handlers:
  - name: disable_service
    systemd: enabled=no name=homebridge.service
