---
- name: Install InfluxDB
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    dashboards: [
          {
            "name": "smarthome",
            "file": "../configs/influxdb.json",
            "dash_name": "Smarthome"
          }
        ]

  tasks:
  - name: trans
    apt:
      name: apt-transport-https
      state: latest

  - name: key
    apt_key:
      url: https://repos.influxdata.com/influxdb.key
      state: present
      validate_certs: False

  - name: repo
    apt_repository:
      repo: deb https://repos.influxdata.com/debian stretch stable
      state: present
      filename: influxdb

  - name: Install
    apt:
      name: influxdb
      state: latest
      update_cache: yes

  - name: Install python
    pip:
      name: influxdb
      executable: pip3

  - name: conf
    blockinfile:
      dest: "/etc/influxdb/influxdb.conf"
      block: |
        [[udp]]
        enabled = true
        bind-address = ":8089"
        database = "smarthome"

  - name: Restart influxdb
    systemd: state=restarted name=influxdb.service
    notify: disable_influx

  - name: influx init
    lineinfile:
      dest: "/root/influx.txt"
      create: yes
      line: CREATE DATABASE smarthome
    ignore_errors: yes

  - name: logfile
    blockinfile:
      dest: "/etc/rsyslog.d/influxdb.conf"
      create: yes
      block: |
        if $programname == 'influxd' then {
          action(type="omfile" file="/var/log/influxdb.log")
          stop
        }
    ignore_errors: yes

  - name: Create db
    shell: "influx < /root/influx.txt"
    async: 40
    poll: 0

  - name: Delete init
    file: path=/root/influx.txt state=absent


  handlers:
  - name: disable_influx
    systemd: enabled=no name=influxdb.service
