---
- name: Install Jackd2
  hosts: public
  remote_user: root
  become_user: root
  become: true

  tasks:

  - name: pid_dir
    file:
      path: /run/jackaudio/
      state: directory
      mode: 0755
      group: smarthome
      owner: audio

  
