---
- name: Install PHP
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Install php
    apt:
      name: php
      state: latest

  - name: Install php-mbstring
    apt: 
      name: php-mbstring
      force: no
      state: latest

  # - name: xml
  #   apt: name=php7.3-xml force=no state=latest

  # - name: Restart php
  #   systemd: state=restarted name=php7.3-fpm.service

  - name: Restart apache2
    systemd: 
      state: restarted
      name: apache2.service
    ignore_errors: yes

  - name: Restart nginx
    systemd: 
      state: restarted
      name: nginx.service
    ignore_errors: yes



  - name: Populate service facts
    service_facts:

  - name: Debug services_facts
    debug:
      var: ansible_facts.services["apache2"]
    debug:
      var: ansible_facts.services["apache2.state"]
