---
- name: Install PHP
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Install php
    apt:
      name: php
      state: latest

  - name: Install php-mbstring
    apt: 
      name: php-mbstring
      force: no
      state: latest

  # - name: xml
  #   apt: name=php7.3-xml force=no state=latest

  # - name: Restart php
  #   systemd: state=restarted name=php7.3-fpm.service

