---
- name: "Include: Create users and groups"
  import_playbook: 10_users_groups.yml

- name: Install KNXD
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Install knxd
    apt:
      name: knxd
      state: latest

  - name: Change Owner of knxd service definition
    file:
      path: /lib/systemd/system/knxd.service
      group: smarthome
      mode: 0664
      state: file

  - name: Change Owner of knxd socket definition
    file:
      path: /lib/systemd/system/knxd.socket
      group: smarthome
      mode: 0664
      state: file

  - name: Copy knxd.conf (with an example)
    copy:
      dest: /etc/knxd.conf
      src: configs/knxd.conf

  - name: Change Owner of knxd.conf
    file:
      path: /etc/knxd.conf
      group: smarthome
      mode: 0664
      state: file

  - name: Copy knxd.ini
    copy:
      dest: /etc/knxd.ini
      src: configs/knxd.ini

  - name: Change Owner of knxd.ini
    file:
      path: /etc/knxd.ini
      group: smarthome
      mode: 0664
      state: file

