---
- name: "Include: Create users and groups"
  import_playbook: 10_users_groups.yml

- name: Install smartVISU
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    branch: develop
    htmlpath: /var/www/html
    smartvisudir: smartvisu

  tasks:
  - name: "Git smartVISU ({{branch}})"
    git:
      repo: 'https://github.com/Martin-Gleiss/smartvisu'
      dest: "{{ htmlpath }}/{{ smartvisudir }}"
      version: "{{ branch }}"
      force: yes
    register: git
  - debug: var=git

  - name: Change Owner of smartVISU installation
    file:
      path: "{{ htmlpath }}/{{ smartvisudir }}"
      owner: smarthome
      group: www-data
      mode: u=rwX,g=rwX,o=rX
      recurse: yes
      state: directory

  - name: mbstring
    apt: name=php-mbstring force=no state=latest

  # - name: xml
  #   apt: name=php7.3-xml force=no state=latest

  # - name: Restart php
  #   systemd: state=restarted name=php7.3-fpm.service

  # - name: Restart nginx
  #   systemd: state=restarted name=nginx

