---
- name: "Include: Create users and groups"
  import_playbook: 10_users_groups.yml

- name: Install smartVISU v2.8
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    branch: develop
    htmlpath: /var/www/html
    smartvisudir: smartvisu28

  tasks:
  - name: Copy Smartvisu v2.8
    unarchive:
      remote_src: yes
      src: https://github.com/Martin-Gleiss/smartvisu/releases/download/v2.8/smartvisu-v2.8_latest.zip
      dest: "{{ htmlpath }}"

  - name: Rename copied smartVISU v2.8 directory
    command: "mv {{ htmlpath }}/smartvisu-master {{ htmlpath }}/{{ smartvisudir }}"

  - name: Change Owner of smartVISU installation
    file:
      path: "{{ htmlpath }}/{{ smartvisudir }}"
      owner: smarthome
      group: www-data
      mode: u=rwX,g=rwX,o=rX
      recurse: yes
      state: directory

  - name: mbstring
    apt: name=php-mbstring force=no state=latest

  # - name: xml
  #   apt: name=php7.3-xml force=no state=latest

  # - name: Restart php
  #   systemd: state=restarted name=php7.3-fpm.service

  # - name: Restart nginx
  #   systemd: state=restarted name=nginx

