---
- name: Create new User
  hosts: all

  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Create Group
    group:
      name: smarthome2
      state: present

  - name: Create User
    user:
      name: smarthome2
      shell: /bin/bash
      group: smarthome2
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'
